HTTP = {
    100: ("Continue", "The server got the request headers; the client should send the body."),
    101: ("Switching Protocols", "The server is switching to the protocol the client asked for, such as WebSocket."),
    102: ("Processing", "WebDAV: the request was received and is still being processed."),
    103: ("Early Hints", "Preload hints sent before the final response."),
    200: ("OK", "The request succeeded."),
    201: ("Created", "The request succeeded and a new resource was created."),
    202: ("Accepted", "The request was accepted for processing, but the processing is not finished."),
    203: ("Non-Authoritative Information", "The response was changed by a proxy."),
    204: ("No Content", "The request succeeded and there is no body to return."),
    205: ("Reset Content", "The client should reset the document view."),
    206: ("Partial Content", "Only part of the resource is sent, as asked for with a Range header."),
    207: ("Multi-Status", "WebDAV: several status codes are returned in the body."),
    208: ("Already Reported", "WebDAV: members of a binding were already listed."),
    226: ("IM Used", "The response is the result of instance manipulations applied to the resource."),
    300: ("Multiple Choices", "There are several representations of the resource to choose from."),
    301: ("Moved Permanently", "The resource has a new permanent URL, given in the Location header."),
    302: ("Found", "The resource is temporarily at another URL."),
    303: ("See Other", "Get the result from another URL with GET."),
    304: ("Not Modified", "The cached copy is still valid."),
    307: ("Temporary Redirect", "Repeat the request at another URL with the same method."),
    308: ("Permanent Redirect", "The resource moved for good; repeat with the same method."),
    400: ("Bad Request", "The server cannot understand the request, for example because of bad syntax."),
    401: ("Unauthorized", "Authentication is missing or not valid."),
    402: ("Payment Required", "Reserved; some APIs use it for billing or quota errors."),
    403: ("Forbidden", "The client is known, but has no permission for this resource."),
    404: ("Not Found", "The server cannot find the resource."),
    405: ("Method Not Allowed", "The resource does not support this HTTP method."),
    406: ("Not Acceptable", "No representation matches the Accept headers."),
    407: ("Proxy Authentication Required", "The client must authenticate with the proxy."),
    408: ("Request Timeout", "The server timed out waiting for the request."),
    409: ("Conflict", "The request conflicts with the current state of the resource."),
    410: ("Gone", "The resource was removed and will not come back."),
    411: ("Length Required", "The request needs a Content-Length header."),
    412: ("Precondition Failed", "A condition in the request headers, such as If-Match, is false."),
    413: ("Content Too Large", "The request body is larger than the server allows."),
    414: ("URI Too Long", "The URL is longer than the server allows."),
    415: ("Unsupported Media Type", "The server does not support the body's format."),
    416: ("Range Not Satisfiable", "The requested range is outside the resource."),
    417: ("Expectation Failed", "The server cannot meet the Expect header."),
    418: ("I'm a teapot", "An April Fools' code from RFC 2324."),
    421: ("Misdirected Request", "The request went to a server that cannot answer for this host."),
    422: ("Unprocessable Content", "The syntax is fine, but the content has semantic errors, such as failed validation."),
    423: ("Locked", "WebDAV: the resource is locked."),
    424: ("Failed Dependency", "WebDAV: the request failed because an earlier request failed."),
    425: ("Too Early", "The server will not process a request that might be replayed."),
    426: ("Upgrade Required", "The client must switch to another protocol, such as TLS."),
    428: ("Precondition Required", "The server needs a conditional request, such as If-Match."),
    429: ("Too Many Requests", "Rate limit reached. Wait, often as long as the Retry-After header says."),
    431: ("Request Header Fields Too Large", "The headers are too big, often because of large cookies."),
    451: ("Unavailable For Legal Reasons", "The resource is blocked for legal reasons."),
    499: ("Client Closed Request", "nginx: the client closed the connection before the response."),
    500: ("Internal Server Error", "The server hit an unexpected error. Check the server logs."),
    501: ("Not Implemented", "The server does not support the functionality the request needs."),
    502: ("Bad Gateway", "A proxy or gateway got a bad response from the upstream server."),
    503: ("Service Unavailable", "The server is overloaded or down for maintenance."),
    504: ("Gateway Timeout", "A proxy or gateway did not get a response from upstream in time."),
    505: ("HTTP Version Not Supported", "The server does not support the HTTP version of the request."),
    507: ("Insufficient Storage", "WebDAV: the server cannot store what the request needs."),
    508: ("Loop Detected", "WebDAV: the server found an infinite loop."),
    511: ("Network Authentication Required", "Sign in to the network first, for example a Wi-Fi captive portal."),
    520: ("Web Server Returned an Unknown Error", "Cloudflare: the origin server sent an unexpected response."),
    521: ("Web Server Is Down", "Cloudflare: the origin server refused the connection."),
    522: ("Connection Timed Out", "Cloudflare: the TCP connection to the origin timed out."),
    524: ("A Timeout Occurred", "Cloudflare: the origin did not send an HTTP response in time."),
}

ERRNO = {
    "EPERM": (1, "Operation not permitted", "The process lacks the privilege for this operation."),
    "ENOENT": (2, "No such file or directory", "A path does not exist. Check the path and the working directory."),
    "ESRCH": (3, "No such process", "The process ID does not exist."),
    "EINTR": (4, "Interrupted system call", "A signal interrupted the call. Retrying is usually correct."),
    "EIO": (5, "Input/output error", "A low-level I/O error, often from the disk or a device."),
    "ENXIO": (6, "No such device or address", "The device is missing or not configured."),
    "E2BIG": (7, "Argument list too long", "The arguments and environment are larger than the system allows."),
    "ENOEXEC": (8, "Exec format error", "The file is not an executable for this system, for example the wrong architecture."),
    "EBADF": (9, "Bad file descriptor", "The file descriptor is closed or not valid."),
    "ECHILD": (10, "No child processes", "There is no child process to wait for."),
    "EAGAIN": (11, "Resource temporarily unavailable", "Try again later; on non-blocking I/O, no data is ready."),
    "EWOULDBLOCK": (11, "Operation would block", "Same as EAGAIN."),
    "ENOMEM": (12, "Cannot allocate memory", "The system or the process is out of memory."),
    "EACCES": (13, "Permission denied", "File permissions do not allow this access."),
    "EFAULT": (14, "Bad address", "A pointer argument points outside the process's memory."),
    "EBUSY": (16, "Device or resource busy", "Something else is using the resource, for example a mounted disk."),
    "EEXIST": (17, "File exists", "The file or directory already exists."),
    "EXDEV": (18, "Invalid cross-device link", "A rename or link across file systems is not possible."),
    "ENODEV": (19, "No such device", "The device does not exist or the operation is not supported on it."),
    "ENOTDIR": (20, "Not a directory", "A part of the path is a file, not a directory."),
    "EISDIR": (21, "Is a directory", "A file operation was used on a directory."),
    "EINVAL": (22, "Invalid argument", "An argument has a value that is not allowed."),
    "ENFILE": (23, "Too many open files in system", "The system-wide open file limit is reached."),
    "EMFILE": (24, "Too many open files", "The process reached its open file limit (ulimit -n)."),
    "ENOTTY": (25, "Inappropriate ioctl for device", "The operation needs a terminal, but the file is not one."),
    "ETXTBSY": (26, "Text file busy", "The executable is being written or is running."),
    "EFBIG": (27, "File too large", "The file is bigger than the file system or limit allows."),
    "ENOSPC": (28, "No space left on device", "The disk or quota is full, or the file system ran out of inodes."),
    "ESPIPE": (29, "Illegal seek", "Seeking is not possible on a pipe, socket or FIFO."),
    "EROFS": (30, "Read-only file system", "The file system is mounted read-only."),
    "EMLINK": (31, "Too many links", "The file has the maximum number of hard links."),
    "EPIPE": (32, "Broken pipe", "The other end of the pipe or socket was closed."),
    "EDOM": (33, "Numerical argument out of domain", "A math function got an argument outside its domain."),
    "ERANGE": (34, "Numerical result out of range", "The result does not fit in the return type."),
    "EDEADLK": (35, "Resource deadlock avoided", "The lock would cause a deadlock."),
    "ENAMETOOLONG": (36, "File name too long", "A path or a path component is too long."),
    "ENOLCK": (37, "No locks available", "The system lock table is full."),
    "ENOSYS": (38, "Function not implemented", "The system call is not available in this kernel or sandbox."),
    "ENOTEMPTY": (39, "Directory not empty", "The directory must be empty for this operation."),
    "ELOOP": (40, "Too many levels of symbolic links", "A symlink loop, or too many links in a row."),
    "ENODATA": (61, "No data available", "There is no data, for example a missing extended attribute."),
    "ETIME": (62, "Timer expired", "A timer or stream timeout expired."),
    "ENOLINK": (67, "Link has been severed", "The remote link is gone."),
    "EPROTO": (71, "Protocol error", "The protocol hit an error."),
    "EOVERFLOW": (75, "Value too large for defined data type", "A value, such as a file size, does not fit."),
    "EILSEQ": (84, "Invalid or incomplete multibyte or wide character", "The text has an encoding error."),
    "EUSERS": (87, "Too many users", "The user quota is exceeded."),
    "ENOTSOCK": (88, "Socket operation on non-socket", "The file descriptor is not a socket."),
    "EDESTADDRREQ": (89, "Destination address required", "A send on a socket that has no destination."),
    "EMSGSIZE": (90, "Message too long", "The message is larger than the socket allows."),
    "EPROTOTYPE": (91, "Protocol wrong type for socket", "The protocol does not match the socket type."),
    "ENOPROTOOPT": (92, "Protocol not available", "The socket option is not supported."),
    "EPROTONOSUPPORT": (93, "Protocol not supported", "The protocol is not available."),
    "EOPNOTSUPP": (95, "Operation not supported", "The operation is not supported on this object."),
    "ENOTSUP": (95, "Operation not supported", "Same as EOPNOTSUPP."),
    "EAFNOSUPPORT": (97, "Address family not supported by protocol", "For example IPv6 on a system without it."),
    "EADDRINUSE": (98, "Address already in use", "Another process is using the port. Find it with ss -ltnp."),
    "EADDRNOTAVAIL": (99, "Cannot assign requested address", "The address is not on this machine."),
    "ENETDOWN": (100, "Network is down", "The network interface is down."),
    "ENETUNREACH": (101, "Network is unreachable", "There is no route to the network."),
    "ENETRESET": (102, "Network dropped connection on reset", "The network reset the connection."),
    "ECONNABORTED": (103, "Software caused connection abort", "This machine aborted the connection."),
    "ECONNRESET": (104, "Connection reset by peer", "The other side closed the connection abruptly."),
    "ENOBUFS": (105, "No buffer space available", "The system ran out of socket buffers."),
    "EISCONN": (106, "Transport endpoint is already connected", "The socket is already connected."),
    "ENOTCONN": (107, "Transport endpoint is not connected", "The socket is not connected."),
    "ESHUTDOWN": (108, "Cannot send after transport endpoint shutdown", "The socket was shut down for writing."),
    "ETIMEDOUT": (110, "Connection timed out", "The other side did not answer in time. Check firewalls and the address."),
    "ECONNREFUSED": (111, "Connection refused", "Nothing is listening on that address and port."),
    "EHOSTDOWN": (112, "Host is down", "The remote host is down."),
    "EHOSTUNREACH": (113, "No route to host", "The host cannot be reached, often because of a firewall."),
    "EALREADY": (114, "Operation already in progress", "A non-blocking operation is already running."),
    "EINPROGRESS": (115, "Operation now in progress", "A non-blocking connect has started."),
    "ESTALE": (116, "Stale file handle", "A network file system handle is no longer valid."),
    "EDQUOT": (122, "Disk quota exceeded", "The user's disk quota is full."),
    "ECANCELED": (125, "Operation canceled", "The operation was canceled."),
    "EOWNERDEAD": (130, "Owner died", "The owner of a robust mutex died."),
}

SIGNALS = {
    1: ("SIGHUP", "Hangup", "The terminal closed, or a daemon was asked to reload."),
    2: ("SIGINT", "Interrupt", "Ctrl+C."),
    3: ("SIGQUIT", "Quit", "Ctrl+\\, quits with a core dump."),
    4: ("SIGILL", "Illegal instruction", "The CPU met an invalid instruction, often a build for the wrong CPU."),
    5: ("SIGTRAP", "Trace trap", "A debugger breakpoint or trap."),
    6: ("SIGABRT", "Aborted", "The program called abort(), often after a failed assertion or heap corruption."),
    7: ("SIGBUS", "Bus error", "Bad memory access, for example to a truncated memory-mapped file."),
    8: ("SIGFPE", "Floating point exception", "An arithmetic error, usually integer division by zero."),
    9: ("SIGKILL", "Killed", "Killed and cannot be caught. Often the out-of-memory killer."),
    10: ("SIGUSR1", "User signal 1", "Defined by the application."),
    11: ("SIGSEGV", "Segmentation fault", "Invalid memory access, such as a null or dangling pointer."),
    12: ("SIGUSR2", "User signal 2", "Defined by the application."),
    13: ("SIGPIPE", "Broken pipe", "Wrote to a pipe or socket with no reader."),
    14: ("SIGALRM", "Alarm clock", "A timer set with alarm() expired."),
    15: ("SIGTERM", "Terminated", "A polite request to stop, as sent by kill and systemd."),
    16: ("SIGSTKFLT", "Stack fault", "Unused on modern Linux."),
    17: ("SIGCHLD", "Child status changed", "A child process stopped or exited."),
    18: ("SIGCONT", "Continued", "Continue a stopped process."),
    19: ("SIGSTOP", "Stopped (signal)", "Stops the process and cannot be caught."),
    20: ("SIGTSTP", "Stopped", "Ctrl+Z."),
    21: ("SIGTTIN", "Stopped (tty input)", "A background process tried to read from the terminal."),
    22: ("SIGTTOU", "Stopped (tty output)", "A background process tried to write to the terminal."),
    23: ("SIGURG", "Urgent I/O condition", "Out-of-band data on a socket."),
    24: ("SIGXCPU", "CPU time limit exceeded", "The process used its CPU time limit."),
    25: ("SIGXFSZ", "File size limit exceeded", "The process wrote past its file size limit."),
    26: ("SIGVTALRM", "Virtual timer expired", "A virtual timer expired."),
    27: ("SIGPROF", "Profiling timer expired", "A profiling timer expired."),
    28: ("SIGWINCH", "Window changed", "The terminal was resized."),
    29: ("SIGIO", "I/O possible", "Asynchronous I/O is ready."),
    30: ("SIGPWR", "Power failure", "A power failure was reported."),
    31: ("SIGSYS", "Bad system call", "A blocked system call, often from a seccomp sandbox."),
}

EXIT = {
    0: "Success.",
    1: "General error. The program failed; check its output.",
    2: "Misuse of a shell builtin, or wrong command-line arguments.",
    126: "The command was found but cannot run, for example it is not executable.",
    127: "Command not found. Check the spelling and PATH.",
    128: "Invalid argument to exit.",
    255: "Exit status out of range, or an SSH connection error.",
}

SQLSTATE_CLASSES = {
    "00": "Successful completion", "01": "Warning", "02": "No data", "03": "SQL statement not yet complete",
    "08": "Connection exception", "09": "Triggered action exception", "0A": "Feature not supported",
    "0B": "Invalid transaction initiation", "0F": "Locator exception", "0L": "Invalid grantor",
    "0P": "Invalid role specification", "0Z": "Diagnostics exception", "20": "Case not found",
    "21": "Cardinality violation", "22": "Data exception", "23": "Integrity constraint violation",
    "24": "Invalid cursor state", "25": "Invalid transaction state", "26": "Invalid SQL statement name",
    "27": "Triggered data change violation", "28": "Invalid authorization specification",
    "2B": "Dependent privilege descriptors still exist", "2D": "Invalid transaction termination",
    "2F": "SQL routine exception", "34": "Invalid cursor name", "38": "External routine exception",
    "39": "External routine invocation exception", "3B": "Savepoint exception", "3D": "Invalid catalog name",
    "3F": "Invalid schema name", "40": "Transaction rollback", "42": "Syntax error or access rule violation",
    "44": "WITH CHECK OPTION violation", "53": "Insufficient resources", "54": "Program limit exceeded",
    "55": "Object not in prerequisite state", "57": "Operator intervention", "58": "System error",
    "72": "Snapshot failure", "F0": "Configuration file error", "HV": "Foreign data wrapper error",
    "P0": "PL/pgSQL error", "XX": "Internal error",
}

SQLSTATE = {
    "00000": ("successful_completion", "The statement succeeded."),
    "01000": ("warning", "A warning was raised."),
    "02000": ("no_data", "The query returned no rows where some were expected."),
    "08000": ("connection_exception", "The connection failed."),
    "08003": ("connection_does_not_exist", "The connection is closed."),
    "08006": ("connection_failure", "The connection to the server was lost."),
    "08001": ("sqlclient_unable_to_establish_sqlconnection", "The client could not connect."),
    "08004": ("sqlserver_rejected_establishment_of_sqlconnection", "The server refused the connection."),
    "08P01": ("protocol_violation", "The client and server disagree on the protocol."),
    "0A000": ("feature_not_supported", "This feature is not supported."),
    "21000": ("cardinality_violation", "A subquery returned more than one row where one was expected."),
    "22001": ("string_data_right_truncation", "The value is too long for the column type, such as varchar(n)."),
    "22003": ("numeric_value_out_of_range", "The number does not fit in the column type."),
    "22007": ("invalid_datetime_format", "The date or time text cannot be parsed."),
    "22008": ("datetime_field_overflow", "A date or time field is out of range."),
    "22012": ("division_by_zero", "Division by zero."),
    "22021": ("character_not_in_repertoire", "The text has bytes that are not valid in the encoding."),
    "22023": ("invalid_parameter_value", "A function got a parameter value it does not accept."),
    "22P02": ("invalid_text_representation", "The text cannot be cast to the type, for example 'abc' to integer or a bad UUID."),
    "22P05": ("untranslatable_character", "A character cannot be converted to the target encoding."),
    "23000": ("integrity_constraint_violation", "A constraint was violated."),
    "23001": ("restrict_violation", "A RESTRICT foreign key blocks this change."),
    "23502": ("not_null_violation", "A NOT NULL column got a null value."),
    "23503": ("foreign_key_violation", "The referenced row does not exist, or other rows still reference this one."),
    "23505": ("unique_violation", "A duplicate value in a column or index that must be unique."),
    "23514": ("check_violation", "A CHECK constraint failed."),
    "23P01": ("exclusion_violation", "An exclusion constraint failed, for example overlapping ranges."),
    "24000": ("invalid_cursor_state", "The cursor is in the wrong state."),
    "25001": ("active_sql_transaction", "This command cannot run inside a transaction block."),
    "25006": ("read_only_sql_transaction", "A write was tried in a read-only transaction or on a replica."),
    "25P02": ("in_failed_sql_transaction", "An earlier statement failed; roll back before running more commands."),
    "28000": ("invalid_authorization_specification", "Authentication failed or is not allowed by pg_hba.conf."),
    "28P01": ("invalid_password", "The password is wrong."),
    "2BP01": ("dependent_objects_still_exist", "Other objects depend on this one; use CASCADE or drop them first."),
    "3D000": ("invalid_catalog_name", "The database does not exist."),
    "3F000": ("invalid_schema_name", "The schema does not exist."),
    "40001": ("serialization_failure", "A concurrent transaction conflicted. Retry the transaction."),
    "40P01": ("deadlock_detected", "Two transactions waited on each other. Retry one of them."),
    "42501": ("insufficient_privilege", "The role lacks permission for this object."),
    "42601": ("syntax_error", "The SQL has a syntax error near the reported position."),
    "42602": ("invalid_name", "The name is not valid."),
    "42622": ("name_too_long", "The identifier is longer than 63 bytes."),
    "42701": ("duplicate_column", "The column already exists."),
    "42702": ("ambiguous_column", "The column name matches more than one table; qualify it."),
    "42703": ("undefined_column", "The column does not exist. Check the name and quoting."),
    "42704": ("undefined_object", "The object, such as a type or role, does not exist."),
    "42710": ("duplicate_object", "The object already exists."),
    "42712": ("duplicate_alias", "A table alias is used twice."),
    "42723": ("duplicate_function", "The function already exists with these arguments."),
    "42725": ("ambiguous_function", "More than one function matches the arguments; add casts."),
    "42803": ("grouping_error", "A column must appear in GROUP BY or be used in an aggregate."),
    "42804": ("datatype_mismatch", "The value has the wrong type for this context."),
    "42809": ("wrong_object_type", "The object is of the wrong kind, such as a view where a table is needed."),
    "42830": ("invalid_foreign_key", "The foreign key does not match a unique key."),
    "42846": ("cannot_coerce", "The value cannot be cast to the type."),
    "42883": ("undefined_function", "No function matches the name and argument types; you may need casts."),
    "42P01": ("undefined_table", "The table or view does not exist, or is not in the search_path."),
    "42P02": ("undefined_parameter", "A query parameter is not defined."),
    "42P04": ("duplicate_database", "The database already exists."),
    "42P06": ("duplicate_schema", "The schema already exists."),
    "42P07": ("duplicate_table", "The table already exists."),
    "42P10": ("invalid_column_reference", "The column reference is not valid, for example in ON CONFLICT."),
    "42P18": ("indeterminate_datatype", "The parameter type cannot be inferred; add a cast."),
    "53000": ("insufficient_resources", "The server is out of resources."),
    "53100": ("disk_full", "The disk is full."),
    "53200": ("out_of_memory", "The server is out of memory."),
    "53300": ("too_many_connections", "max_connections is reached. Use a connection pool."),
    "54000": ("program_limit_exceeded", "A limit was exceeded."),
    "54001": ("statement_too_complex", "The statement is too complex."),
    "55000": ("object_not_in_prerequisite_state", "The object is not in the state this needs."),
    "55006": ("object_in_use", "The object is in use by another session."),
    "55P03": ("lock_not_available", "A lock could not be taken, for example with NOWAIT or lock_timeout."),
    "57014": ("query_canceled", "The query was canceled, often by statement_timeout."),
    "57P01": ("admin_shutdown", "The server is shutting down."),
    "57P03": ("cannot_connect_now", "The server is starting up or in recovery."),
    "58030": ("io_error", "The server hit an I/O error."),
    "P0001": ("raise_exception", "A RAISE EXCEPTION in PL/pgSQL."),
    "P0002": ("no_data_found", "A SELECT INTO STRICT returned no rows."),
    "P0003": ("too_many_rows", "A SELECT INTO STRICT returned more than one row."),
    "XX000": ("internal_error", "An internal server error."),
    "XX001": ("data_corrupted", "Data corruption was found."),
}

HRESULT = {
    0x80004001: ("E_NOTIMPL", "Not implemented."),
    0x80004002: ("E_NOINTERFACE", "The interface is not supported."),
    0x80004003: ("E_POINTER", "A pointer is not valid."),
    0x80004004: ("E_ABORT", "The operation was aborted."),
    0x80004005: ("E_FAIL", "Unspecified failure."),
    0x8000FFFF: ("E_UNEXPECTED", "Catastrophic failure."),
    0x80070002: ("ERROR_FILE_NOT_FOUND", "The system cannot find the file."),
    0x80070003: ("ERROR_PATH_NOT_FOUND", "The system cannot find the path."),
    0x80070005: ("E_ACCESSDENIED", "Access is denied."),
    0x80070006: ("E_HANDLE", "The handle is not valid."),
    0x8007000E: ("E_OUTOFMEMORY", "Not enough memory."),
    0x80070057: ("E_INVALIDARG", "One or more arguments are not valid."),
    0x80070020: ("ERROR_SHARING_VIOLATION", "Another process is using the file."),
    0x80070070: ("ERROR_DISK_FULL", "There is not enough space on the disk."),
    0x800700B7: ("ERROR_ALREADY_EXISTS", "The file already exists."),
    0x800704C7: ("ERROR_CANCELLED", "The operation was canceled by the user."),
    0x80070422: ("ERROR_SERVICE_DISABLED", "The service is disabled."),
    0x80070643: ("ERROR_INSTALL_FAILURE", "A fatal error during installation."),
    0x800706BA: ("RPC_S_SERVER_UNAVAILABLE", "The RPC server is unavailable."),
    0x80072EE2: ("ERROR_INTERNET_TIMEOUT", "The network request timed out."),
    0x80072EE7: ("ERROR_INTERNET_NAME_NOT_RESOLVED", "The server name could not be resolved."),
    0x80072EFD: ("ERROR_INTERNET_CANNOT_CONNECT", "A connection to the server could not be made."),
    0x8024402C: ("WU_E_PT_WINHTTP_NAME_NOT_RESOLVED", "Windows Update could not resolve the server name."),
    0x80240017: ("WU_E_NOT_APPLICABLE", "The update does not apply to this computer."),
    0x80131500: ("COR_E_EXCEPTION", ".NET: a general exception."),
    0x80131509: ("COR_E_INVALIDOPERATION", ".NET: InvalidOperationException."),
    0x800401F0: ("CO_E_NOTINITIALIZED", "CoInitialize has not been called."),
    0x80040154: ("REGDB_E_CLASSNOTREG", "The COM class is not registered."),
    0x8001010E: ("RPC_E_WRONG_THREAD", "The object was called from the wrong thread."),
    0xC0000005: ("STATUS_ACCESS_VIOLATION", "NTSTATUS: invalid memory access, the Windows segfault."),
    0xC0000409: ("STATUS_STACK_BUFFER_OVERRUN", "NTSTATUS: a stack buffer overrun or a fast-fail."),
    0xC00000FD: ("STATUS_STACK_OVERFLOW", "NTSTATUS: stack overflow, often infinite recursion."),
    0xC0000135: ("STATUS_DLL_NOT_FOUND", "NTSTATUS: a required DLL is missing."),
    0xC0000142: ("STATUS_DLL_INIT_FAILED", "NTSTATUS: a DLL failed to initialise."),
}

FACILITIES = {0: "Null", 1: "RPC", 2: "Dispatch", 3: "Storage", 4: "ITF (COM interface)", 7: "Win32", 8: "Windows",
              9: "Security", 10: "Control", 11: "Certificates", 13: "Media server", 23: "URL moniker",
              24: "WinRM", 25: "WinHTTP/Win Update", 0x13: ".NET (COR)"}

EXCEPTIONS = {
    "KeyError": ("Python", "A dict lookup used a key that is not in the dict. Use .get() or check with in."),
    "IndexError": ("Python", "A list or tuple index is out of range."),
    "AttributeError": ("Python", "The object has no attribute with that name, often because a value is None."),
    "TypeError": ("Python", "An operation got a value of the wrong type, or a function got wrong arguments."),
    "ValueError": ("Python", "The type is right, but the value is not acceptable, such as int('abc')."),
    "NameError": ("Python", "A name is used before it is defined, or is misspelled."),
    "ImportError": ("Python", "A name could not be imported from a module."),
    "ModuleNotFoundError": ("Python", "The module is not installed in this environment, or the name is wrong."),
    "ZeroDivisionError": ("Python", "Division or modulo by zero."),
    "FileNotFoundError": ("Python", "The file does not exist (ENOENT)."),
    "PermissionError": ("Python", "The operation is not permitted (EACCES or EPERM)."),
    "RecursionError": ("Python", "The maximum recursion depth was exceeded, often infinite recursion."),
    "UnicodeDecodeError": ("Python", "Bytes could not be decoded with this encoding; check the file's encoding."),
    "UnicodeEncodeError": ("Python", "Text could not be encoded with this encoding."),
    "StopIteration": ("Python", "next() was called on an exhausted iterator."),
    "AssertionError": ("Python", "An assert statement failed."),
    "NotImplementedError": ("Python", "A method that should be overridden was called."),
    "TimeoutError": ("Python", "An operation timed out (ETIMEDOUT)."),
    "ConnectionRefusedError": ("Python", "Nothing is listening on that address and port."),
    "ConnectionResetError": ("Python", "The other side closed the connection abruptly."),
    "OSError": ("Python", "A system call failed; see the errno in the message."),
    "MemoryError": ("Python", "The process ran out of memory."),
    "IndentationError": ("Python", "The indentation is wrong, often mixed tabs and spaces."),
    "SyntaxError": ("Python", "The code cannot be parsed."),
    "JSONDecodeError": ("Python", "The text is not valid JSON; check what the server actually returned."),
    "NullPointerException": ("Java", "A method or field was used on a null reference."),
    "ArrayIndexOutOfBoundsException": ("Java", "An array index is negative or past the end."),
    "IndexOutOfBoundsException": ("Java", "An index into a list or string is out of range."),
    "ClassCastException": ("Java", "An object was cast to a type it is not."),
    "IllegalArgumentException": ("Java", "A method got an argument it does not accept."),
    "IllegalStateException": ("Java", "A method was called at the wrong time for the object's state."),
    "NumberFormatException": ("Java", "A string could not be parsed as a number."),
    "ConcurrentModificationException": ("Java", "A collection was changed while being iterated."),
    "UnsupportedOperationException": ("Java", "The operation is not supported, often on an immutable list."),
    "ClassNotFoundException": ("Java", "The class is not on the classpath."),
    "NoClassDefFoundError": ("Java", "A class was present at compile time but is missing at run time."),
    "OutOfMemoryError": ("Java", "The heap or metaspace is full; raise -Xmx or find the leak."),
    "StackOverflowError": ("Java", "The call stack is too deep, often infinite recursion."),
    "NoSuchElementException": ("Java", "There is no next element, for example from an empty Optional or iterator."),
    "InterruptedException": ("Java", "A waiting thread was interrupted."),
    "IOException": ("Java", "An I/O operation failed."),
    "SQLException": ("Java", "A database operation failed; see the SQLState."),
    "NullReferenceException": (".NET", "A member was used on a null reference."),
    "ArgumentNullException": (".NET", "A null was passed where a value is required."),
    "ArgumentOutOfRangeException": (".NET", "An argument is outside the allowed range."),
    "ArgumentException": (".NET", "An argument is not valid."),
    "InvalidOperationException": (".NET", "The call is not valid for the object's current state."),
    "InvalidCastException": (".NET", "The cast is not valid."),
    "FormatException": (".NET", "A string is not in the right format, for example for int.Parse."),
    "KeyNotFoundException": (".NET", "The key is not in the dictionary."),
    "ObjectDisposedException": (".NET", "The object was used after Dispose."),
    "TaskCanceledException": (".NET", "A task was canceled, often by a timeout on HttpClient."),
    "DbUpdateException": (".NET", "Entity Framework could not save changes; see the inner exception."),
    "ReferenceError": ("JavaScript", "A variable is used that is not defined."),
    "RangeError": ("JavaScript", "A value is outside the allowed range, such as an array length."),
    "UnhandledPromiseRejection": ("JavaScript", "A promise was rejected and nothing caught it."),
    "PanicException": ("Rust", "A thread panicked."),
}

GO_RUST = {
    "nil pointer dereference": ("Go", "A nil pointer, map or interface was used. Check for nil before using it."),
    "index out of range": ("Go / Rust", "A slice or array index is past its length."),
    "concurrent map writes": ("Go", "Two goroutines wrote to a map at the same time; use a mutex or sync.Map."),
    "all goroutines are asleep - deadlock": ("Go", "Every goroutine is blocked, usually on a channel."),
    "called `Option::unwrap()` on a `None` value": ("Rust", "unwrap() on None. Handle the None case."),
    "called `Result::unwrap()` on an `Err` value": ("Rust", "unwrap() on an Err. Handle or propagate the error with ?."),
    "already borrowed: BorrowMutError": ("Rust", "A RefCell was borrowed mutably while another borrow was active."),
    "attempt to subtract with overflow": ("Rust", "Integer overflow in a debug build."),
    "Segmentation fault": ("Unix", "Invalid memory access (SIGSEGV)."),
    "Killed": ("Unix", "The process got SIGKILL, often from the out-of-memory killer."),
    "Out of memory: Killed process": ("Linux", "The kernel's out-of-memory killer stopped a process."),
    "command not found": ("Shell", "The command is not installed or not in PATH."),
    "Permission denied (publickey)": ("SSH", "The server did not accept any of your keys. Check ssh-add -l and the user name."),
    "Host key verification failed": ("SSH", "The host key is unknown or changed. Check known_hosts."),
    "CORS": ("Browser", "The server did not send the Access-Control-Allow-Origin header this page needs."),
}
